apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydiningfrontend
spec:
  selector:
    matchLabels:
      app: mydiningfrontend
  replicas: 1  # Adjust the number of replicas as needed
  template:
    metadata:
      labels:
        app: mydiningfrontend
    spec:
      containers:
      - name: mydiningfrontend
        image: vishwatejach/mydiningfrontend:latest
        ports:
        - containerPort: 3000  # Adjust the port if your React app runs on a different port
---
apiVersion: v1
kind: Service
metadata:
  name: mydiningfrontend
spec:
  type: NodePort
  selector:
    app: mydiningfrontend
  ports:
  - name: http
    port: 80  # Expose on port 80 if it's a web application
    targetPort: 3000  # Adjust if your React app runs on a different port
    nodePort: 30700