apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydining
spec:
  selector:
    matchLabels:
      app: mydining
  template:
    metadata:
      labels:
        app: mydining
    spec:
      containers:
      - name: mydining-backend
        image: vishwatejach/spebackend:v2
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB_NAME
          value: mydining
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mydiningsecret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydiningsecret
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: mydining
spec:
  type: NodePort
  selector:
    app: mydining
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30500
